# Numpy 

Whenever we do numerical calculation then we use this library 

In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)
# it goves a datas as it is 

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [1,2,3,4,True,34.345,'sonu']

In [43]:
a0 = np.array(l1)
# it is converted to data in a string format
a0

array(['1', '2', '3', '4', 'True', '34.345', 'sonu'], dtype='<U32')

In [13]:
a1 = np.array([[1,2,3],[4,5,6]])

In [12]:
a2 = np.array([[[1,2,3],[2,3,4],[3,4,5]]])

In [14]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]]])

In [16]:
a1.ndim

2

In [17]:
a2.ndim

3

In [18]:
a1.size

6

In [19]:
a2.size

9

In [20]:
a1.shape

(2, 3)

In [21]:
a2.shape

(1, 3, 3)

In [23]:
# for random dataset 
np.random.randint(1,10,(4,4,4))

array([[[5, 3, 6, 9],
        [8, 8, 7, 2],
        [6, 1, 1, 7],
        [8, 9, 6, 1]],

       [[4, 8, 6, 7],
        [6, 4, 5, 9],
        [4, 5, 6, 6],
        [7, 9, 8, 4]],

       [[5, 1, 1, 1],
        [8, 9, 7, 3],
        [7, 7, 1, 4],
        [8, 3, 7, 1]],

       [[8, 7, 9, 7],
        [6, 9, 8, 7],
        [2, 9, 6, 8],
        [3, 5, 1, 6]]])

In [27]:
np.random.rand(2,5,4)
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].

array([[[0.75262582, 0.41969671, 0.25348936, 0.14508592],
        [0.46800194, 0.14628466, 0.37651568, 0.22695133],
        [0.42154135, 0.14896572, 0.49939017, 0.54580267],
        [0.61902557, 0.14749383, 0.41868941, 0.92457355],
        [0.62974018, 0.82834489, 0.8783458 , 0.12701654]],

       [[0.56789869, 0.99336522, 0.07300223, 0.19426917],
        [0.38697984, 0.24692223, 0.73332291, 0.39749449],
        [0.11014791, 0.39696912, 0.72679883, 0.39191108],
        [0.56066127, 0.92647243, 0.41025432, 0.99598798],
        [0.58218528, 0.63472977, 0.56800577, 0.53082616]]])

In [34]:
a3 = np.random.randn(4,4)
# Return a sample (or samples) from the "standard normal" distribution.
# where Mean (μ) = 0, Standard Deviation (σ) = 1

In [35]:
a3

array([[-0.19644628, -0.93290957,  0.6207869 , -0.58287966],
       [ 0.89799083, -0.1519477 , -0.98347448, -0.81312   ],
       [ 0.40009291,  1.62968312,  1.18302634,  0.55666733],
       [-1.16909337,  0.32722464,  0.25995834,  1.87886064]])

In [37]:
a3.reshape(2,8)

array([[-0.19644628, -0.93290957,  0.6207869 , -0.58287966,  0.89799083,
        -0.1519477 , -0.98347448, -0.81312   ],
       [ 0.40009291,  1.62968312,  1.18302634,  0.55666733, -1.16909337,
         0.32722464,  0.25995834,  1.87886064]])

In [38]:
a3.reshape(1,16)

array([[-0.19644628, -0.93290957,  0.6207869 , -0.58287966,  0.89799083,
        -0.1519477 , -0.98347448, -0.81312   ,  0.40009291,  1.62968312,
         1.18302634,  0.55666733, -1.16909337,  0.32722464,  0.25995834,
         1.87886064]])

In [39]:
a3.reshape(2, -1)

array([[-0.19644628, -0.93290957,  0.6207869 , -0.58287966,  0.89799083,
        -0.1519477 , -0.98347448, -0.81312   ],
       [ 0.40009291,  1.62968312,  1.18302634,  0.55666733, -1.16909337,
         0.32722464,  0.25995834,  1.87886064]])

In [41]:
a3.reshape(1,1,4,2,2)

array([[[[[-0.19644628, -0.93290957],
          [ 0.6207869 , -0.58287966]],

         [[ 0.89799083, -0.1519477 ],
          [-0.98347448, -0.81312   ]],

         [[ 0.40009291,  1.62968312],
          [ 1.18302634,  0.55666733]],

         [[-1.16909337,  0.32722464],
          [ 0.25995834,  1.87886064]]]]])

In [44]:
a0

array(['1', '2', '3', '4', 'True', '34.345', 'sonu'], dtype='<U32')

In [45]:
a0[0]

'1'

In [48]:
a0[2:6:2]

array(['3', 'True'], dtype='<U32')

In [49]:
a0[::-1]

array(['sonu', '34.345', 'True', '4', '3', '2', '1'], dtype='<U32')

In [50]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a2

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]]])

In [56]:
a1[:,1:]

array([[2, 3],
       [5, 6]])

In [58]:
a1[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [59]:
a1[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [60]:
a5 = np.random.randint(2,90,(6,5))

In [61]:
a5

array([[ 2, 48, 71, 61, 73],
       [14, 76, 26, 81, 26],
       [51, 37, 28, 57, 84],
       [33, 31, 64, 72,  4],
       [73, 78, 77, 76,  3],
       [79,  5, 21,  5, 59]])

In [62]:
a5[a5>50]

array([71, 61, 73, 76, 81, 51, 57, 84, 64, 72, 73, 78, 77, 76, 79, 59])

In [64]:
a5[0,1] = 100

In [65]:
a5

array([[  2, 100,  71,  61,  73],
       [ 14,  76,  26,  81,  26],
       [ 51,  37,  28,  57,  84],
       [ 33,  31,  64,  72,   4],
       [ 73,  78,  77,  76,   3],
       [ 79,   5,  21,   5,  59]])

In [66]:
a6 = np.random.randint(0,3,(3,3))

a7 = np.random.randint(0,3,(3,3))

In [67]:
a6

array([[2, 2, 0],
       [0, 0, 1],
       [0, 1, 1]])

In [68]:
a7

array([[0, 1, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [69]:
a6*a7

array([[0, 2, 0],
       [0, 0, 1],
       [0, 2, 1]])

In [70]:
a6@a7

array([[4, 6, 4],
       [2, 2, 1],
       [4, 4, 2]])

In [71]:
a6+100

array([[102, 102, 100],
       [100, 100, 101],
       [100, 101, 101]])

In [72]:
a6/0

/var/folders/d4/vrqxqq1s1pv5l1d9x4mz_m6c0000gn/T/ipykernel_86803/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
/var/folders/d4/vrqxqq1s1pv5l1d9x4mz_m6c0000gn/T/ipykernel_86803/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, nan],
       [nan, nan, inf],
       [nan, inf, inf]])

In [73]:
a6**3

array([[8, 8, 0],
       [0, 0, 1],
       [0, 1, 1]])

In [74]:
a8 = np.zeros((4,4))

In [75]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
a9 = np.ones((4,5))

In [78]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [81]:
np.array([[1,2,3,4]]).T + a9 

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [82]:
a6

array([[2, 2, 0],
       [0, 0, 1],
       [0, 1, 1]])

In [83]:
a6.T

array([[2, 0, 0],
       [2, 0, 1],
       [0, 1, 1]])

In [84]:
np.sqrt(a5)

array([[ 1.41421356, 10.        ,  8.42614977,  7.81024968,  8.54400375],
       [ 3.74165739,  8.71779789,  5.09901951,  9.        ,  5.09901951],
       [ 7.14142843,  6.08276253,  5.29150262,  7.54983444,  9.16515139],
       [ 5.74456265,  5.56776436,  8.        ,  8.48528137,  2.        ],
       [ 8.54400375,  8.83176087,  8.77496439,  8.71779789,  1.73205081],
       [ 8.88819442,  2.23606798,  4.58257569,  2.23606798,  7.68114575]])

In [85]:
np.exp(a5)

array([[7.38905610e+00, 2.68811714e+43, 6.83767123e+30, 3.10429794e+26,
        5.05239363e+31],
       [1.20260428e+06, 1.01480039e+33, 1.95729609e+11, 1.50609731e+35,
        1.95729609e+11],
       [1.40934908e+22, 1.17191424e+16, 1.44625706e+12, 5.68572000e+24,
        3.02507732e+36],
       [2.14643580e+14, 2.90488497e+13, 6.23514908e+27, 1.85867175e+31,
        5.45981500e+01],
       [5.05239363e+31, 7.49841700e+33, 2.75851345e+33, 1.01480039e+33,
        2.00855369e+01],
       [2.03828107e+34, 1.48413159e+02, 1.31881573e+09, 1.48413159e+02,
        4.20121040e+25]])

In [86]:
np.log10(a5)

array([[0.30103   , 2.        , 1.85125835, 1.78532984, 1.86332286],
       [1.14612804, 1.88081359, 1.41497335, 1.90848502, 1.41497335],
       [1.70757018, 1.56820172, 1.44715803, 1.75587486, 1.92427929],
       [1.51851394, 1.49136169, 1.80617997, 1.8573325 , 0.60205999],
       [1.86332286, 1.8920946 , 1.88649073, 1.88081359, 0.47712125],
       [1.89762709, 0.69897   , 1.32221929, 0.69897   , 1.77085201]])

In [87]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [88]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [91]:
np.linspace(2,3,num=50, retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [92]:
np.logspace(2,4,num = 4,base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [95]:
np.eye(5)
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
# identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])